INPUT_MODEL=input_models/book_v7a.bp
OUTPUT_PREFIX=output_meshes/book_v7a_stable_book
BUILD_DIR=build

ADAPTIVE_MODE=research_debug
ADAPTIVE_INTENSITY=0.02
ADAPTIVE_QUALITY_PRIORITY=0.95
ADAPTIVE_MAX_STEPS=4
ADAPTIVE_TARGET_GROWTH=1.05

NUM_PROCESSES=1
NUM_THREADS=1
WRITE_MODE=h
USE_TEMPLATE=y
EXECUTABLE=bin/ap_mesh.exe
